---
# PostgreSQL9.4のリポジトリをインストール
- name: install PostgreSQL9.4 repository
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-1.noarch.rpm state=present
- name: disable PostgreSQL9.4 repository
  lineinfile: dest=/etc/yum.repos.d/pgdg-94-centos.repo regexp='^enabled=1' line='enabled=0' state=present
# postgresql94のインストール
- name: install postgresql94
  yum: name={{ item }} enablerepo=pgdg94 state=present
  with_items:
  - postgresql94-server
  - postgresql94-contrib
# 自動起動の設定
- name: enable postgresql94
  service: name=postgresql-9.4 enabled=yes
# 設定済みかの確認
- name: check postgresql.conf
  command: test -f "/var/lib/pgsql/9.4/data/postgresql.conf"
  register: is_initialized
  ignore_errors: true
# 初期化
- name: initdb
  command: env PGSETUP_INITDB_OPTIONS='--no-locale --encoding=UTF8' /usr/pgsql-9.4/bin/postgresql94-setup initdb
  when: is_initialized|failed
- name: config pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/var/lib/pgsql/9.4/data/pg_hba.conf
  when: is_initialized|failed
- name: config postgresql.conf
  copy: src=postgresql.conf dest=/var/lib/pgsql/9.4/data/postgresql.conf
  when: is_initialized|failed
# サービス起動
- name: start postgresql94
  service: name=postgresql-9.4 state=started
# postgresユーザのパスワード初期化
- name: config postgres password
  command: sudo -u postgres /usr/bin/psql -U postgres -c "ALTER USER postgres with unencrypted password 'postgres';"
  when: is_initialized|failed
# アクセス方法をmd5に変更して再起動
- name: config pg_hba.conf
  template: src=pg_hba.conf2.j2 dest=/var/lib/pgsql/9.4/data/pg_hba.conf
  when: is_initialized|failed
# サービス再起動
- name: start postgresql94
  service: name=postgresql-9.4 state=restarted
  when: is_initialized|failed
