---
# phpのインストール
- name: install php
  yum: name={{ item }} state=present
  with_items:
  - php
  - php-pear
  - php-devel
  - php-xml
  - php-mbstring
  - php-pgsql
  - php-gd
  - php-mysqlnd
  - php-mcrypt
  - php-pecl-zendopcache
  - php-intl
# ここから https://gist.github.com/debility/8838906 を反映
- name: config PHP 1
  copy: src=my.ini dest=/etc/php.d/my.ini owner=root group=root
- name: config PHP 2
  copy: src=timezone.ini dest=/etc/php.d/timezone.ini owner=root group=root
- name: restart httpd
  service: name=httpd state=restarted
